services:
  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    configs:
      - source: qdrant_config
        target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_collections:/qdrant/storage/collections

  backend_ui:
    build:
      context: ./backend_ui
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend_ui:/app
    depends_on:
      - qdrant


configs:
  qdrant_config:
    content: |
      log_level: INFO